### ISSUE TITLE
banned people can send scaps

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#114] opened 2016-02-05 17:21 UTC
someone got banned for spamming scap and is still sending them even though they are banned

Bug reported by 'snip' (STEAM_0:1:20654783).

**Comment by CassiaPurple** [comment] 2016-02-05 20:02
Please do something about it I was playing yesterday and was being spammed by the person in question who got banned

**Comment by ghost** [comment] 2016-02-05 21:30
wasnt there already an issue about this

**Comment by CassiaPurple** [comment] 2016-02-05 22:43
No but there was one about adding the ability to disable scap altogether

**Comment by Lixquid** [comment] 2016-02-05 23:38
Duplicate of #78

**Closed as completed by Lixquid** 2016-02-05 23:38 UTC
Labels: duplicate, enhancement, usersubmitted

**Comment by CassiaPurple** [comment] 2016-02-06 06:35
Oh it was a duplicate oop
