### ISSUE TITLE
advdupe2 can only paste effects if you're admin

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#289] opened 2018-07-26 20:58 UTC
also happens with normal Duplicator

`!p scripted_ents.GetStored'prop_effect'.t.Spawnable = false` to simulate this bug before a bad temporary fix

Bug reported by 'SpiralP' (STEAM_0:1:29289722).

**Comment by ghost** [comment] 2021-05-19 00:07
Still happens or fixed?

**Comment by cdr1996** [comment] 2022-02-24 22:55
I got a player to both try with advdupe2 and the normal duplicator and wasn't able to reproduce this, both the duplicator and advdupe2 could paste it so it was either fixed somewhere along the line or for some reason not reproducable. Closing, but feel free to open again if this resurfaces.

**Closed as completed by cdr1996** 2022-02-24 22:55 UTC
Labels: usersubmitted, fixed?
