### ISSUE TITLE
:you: should not count as a mention

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#448] opened 2020-08-23 17:44 UTC
Especially it should not trigger the afk mention popup thing.

Bug reported by 'PotcFdk' (STEAM_0:1:30490065).

**Comment by ghost** [comment] 2021-01-26 02:45
Hoping earu will get on this

**Comment by cdr1996** [comment] 2022-02-24 23:29
Still relevant as of today from what I've seen. @Earu ?

**Comment by Earu** [comment] 2022-02-24 23:36
working as intended

**Comment by cdr1996** [comment] 2022-02-24 23:37
💀

**Comment by cdr1996** [comment] 2022-03-11 00:41
Closing for now, I personally don't like the :you: thing causing a mention, but Earu doesn't seem intent on changing this. Reopen if needed.

**Closed as completed by cdr1996** 2022-03-11 00:41 UTC
Labels: usersubmitted
