### ISSUE TITLE
notagain/goluwa/libraries/client/common_audio.lua:18: bad argument #1 to 'ipairs' (table expected, got nil)

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#415] opened 2019-08-25 21:42 UTC
[ERROR] notagain/goluwa/libraries/client/common_audio.lua:18: bad argument #1 to 'ipairs' (table expected, got nil)
  1. ipairs - [C]:-1
   2. ExecuteEventQueue - notagain/goluwa/libraries/client/common_audio.lua:18
    3. SetSoundObject - notagain/goluwa/libraries/client/common_audio.lua:26
     4. OnLoad - notagain/goluwa/libraries/client/common_audio.lua:262
      5. HandleLoadedBrowserMessage - notagain/essential/libraries/client/webaudio.lua:1014
       6. HandleBrowserMessage - notagain/essential/libraries/client/webaudio.lua:727
        7. unknown - notagain/essential/libraries/client/webaudio.lua:195

Bug reported by '<color=143,0,0>Crabby<color=255,94,94>Stork' (STEAM_0:0:54038091).

**Comment by Etothepowerof26** [comment] 2019-08-25 21:45
Duplicate of https://github.com/Metastruct/issues/issues/411

**Comment by Etothepowerof26** [comment] 2019-08-25 21:46
I don't even know anymore please help me

**Comment by PotcFdk** [comment] 2019-08-26 16:29
Duplicate of #411

**Closed as completed by PotcFdk** 2019-08-26 16:29 UTC
Labels: duplicate, usersubmitted

**Comment by Etothepowerof26** [comment] 2019-08-26 22:11
thanks
