### ISSUE TITLE
Achievement names/descriptions not showing up right

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#138] opened 2016-04-02 01:45 UTC
![](https://my.mixtape.moe/ejykle.png)
![](https://my.mixtape.moe/zfexvb.png)

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by ghost** [comment] 2016-04-02 01:47
![](http://puu.sh/o2NWq/a576671354.jpg)

**Comment by PotcFdk** [comment] 2016-04-12 16:29
It's caused by some fuckup in the net library. @Python1320 please keep me updated.

**Comment by PotcFdk** [comment] 2016-04-12 16:47
@Python1320 reverted it in r12129 - seems to be fixed now.

**Closed as completed by PotcFdk** 2016-04-12 16:47 UTC
Labels: bug, usersubmitted
