### ISSUE TITLE
right clicking somebody's profile picture on the scoreboard causes a error

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#316] opened 2019-01-01 11:32 UTC
[ERROR] lua/helpers/steamid_helpers.lua:49: attempt to call field 'Add' (a nil value)

Bug reported by 'loser' (STEAM_0:1:104332977).

**Comment by jule14** [comment] 2019-01-01 11:33
yes

**Comment by Etothepowerof26** [comment] 2019-01-01 15:29
can't reproduce, apparently said only happened on one person and that was a couple days ago

**Comment by PotcFdk** [comment] 2019-01-14 17:29
Re-open if it happens again.

**Comment by Zeni44** [comment] 2019-01-27 21:37
This is now fixed

**Closed as completed by Zeni44** 2019-01-27 21:37 UTC
Labels: bug, usersubmitted
